baseURL: https://moritzgort.netlify.app/
languageCode: en-us
title: Portfolio website of Moritz
# theme: showfolio-hugo-theme-main
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      TAKE A LOOK AT MY WEBSITE TO FIND OUT MORE ABOUT MY HOBBIES AND INTERESTS
    title: Hi, my name is Moritz
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Regent's Park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email: gort.moritz@gmail.com
      - email: moritz@gort.com
        title: Email
    enable: yes
    phone:
      - phone: +41 44 44 4444
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: lbs_logo.jpg
  footer:
    copyright: Moritz Gort
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100000682008678
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/moritzgort
      - icon: fa-github
        label: GitHub
        url: https://github.com/moritzgort
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/moritzgort
  image: ''
  name: Moritz Gort
  navigation:
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/aboutme
      - name: Sports
        url: blogs/sports
      - name: Photography
        url: blogs/photography
      - name: Weather anomalies
        url: blogs/weather_anomalies
      - name: Cities
        url: blogs/cities
    menu: Menu
    subtitle: Gort
    title: Moritz
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Get an insight into who I am
        title: About me
        url: blogs/aboutme
      - image: sports.jpg
        subtitle: See which sports I like
        title: Sports
        url: blogs/sports
      - image: photography.jpg
        subtitle: Take a look at some of the photos I took
        title: Photography
        url: blogs/photography
      - image: weather.jpg
        subtitle: Get an insight into weather anomalies
        title: Weather Anomalies
        url: blogs/weather_anomalies
      - image: amsterdam.jpg
        subtitle: See some of my favorite cities
        title: Cities
        url: blogs/cities
  two:
    #buttonText: Start here
    #enable: yes
    subtitle: "If you want to get in touch fill out the form below to send me a message"
    title: Get to know me better
    #url: blogs