---
title: "Amsterdam Airbnb Insights"
date: "14 Oct 2021"
author: "Moritz Gort"
output:
  html_document:
    highlight: zenburn
    theme: flatly
    toc: yes
    toc_float: yes
    number_sections: yes
    code_folding: show
---


```{r setup, include=FALSE}
# leave this chunk alone
options(knitr.table.format = "html") 
knitr::opts_chunk$set(warning = FALSE, message = FALSE, 
  comment = NA, dpi = 300)
```


```{r load-libraries, echo=FALSE}

library(tidyverse) # the usual stuff: dplyr, readr, and other goodies
library(lubridate) # to handle dates
library(GGally) # for correlation-scatter plot matrix
library(ggfortify) # to produce residual diagnostic plots
library(rsample) # to split dataframe in training- & testing sets
library(janitor) # clean_names()
library(broom) # use broom:augment() to get tidy table with regression output, residuals, etc
library(huxtable) # to get summary table of all models produced
library(kableExtra) # for formatting tables
library(moderndive) # for getting regression tables
library(skimr) # for skim
library(mosaic)
library(leaflet) # for interactive HTML maps
library(tidytext)
library(viridis)
library(vroom)
library(rsample)
library(car)
```

```{r load_data, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}

# use cache=TRUE so you dont donwload the data everytime you knit

listings <- vroom("http://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/2021-09-07/data/listings.csv.gz") %>% 
       clean_names()

```

```{r}

# glimpse(listings)
# favstats(listings$id)
# skim(listings)

listings_clean <- listings %>% 
  filter(name != "",
         host_location != "") %>% 
  mutate(price = parse_number(price),
         bathrooms = parse_number(gsub( "\\s.*", "", bathrooms_text))) %>% 
  filter(bathrooms != "")

# typeof(listings_clean$price)
# 
# skim(listings_clean)

# ggplot(listings) +
#   geom_boxplot(aes(x=bedrooms))
# 
# ggplot(listings) +
#   geom_boxplot(aes(x=beds))

listings_clean <- listings_clean %>% 
  filter(bedrooms <= 2,
         beds <= 2,
         minimum_nights <= 4,
         maximum_nights >= 4,
         price <= 1500, # Everything above that would be extraordinarily expensive
         accommodates >= 2)

# ggplot(listings_clean) +
#   geom_boxplot(aes(x=bedrooms))


listings_smaller <- listings_clean %>% 
  select(host_location,
         neighbourhood,
         neighbourhood_cleansed,
         neighbourhood_group_cleansed,
         property_type,
         room_type,
         accommodates,
         bathrooms,
         bathrooms_text,
         bedrooms,
         beds,
         price,
         review_scores_rating,
         minimum_nights,
         maximum_nights,
         property_type,
         latitude,
         longitude,
         host_is_superhost,
         instant_bookable,
         availability_30,
         reviews_per_month)

# listings_smaller %>% 
#   select(price, bedrooms, beds, bathrooms, review_scores_rating) %>% 
#   ggpairs(aes(alpha = 0.4))

# ggplot(listings_smaller, aes(x = price)) +
#   geom_boxplot() +
#   facet_wrap(~bedrooms)

# ggplot(listings_smaller, aes(x = review_scores_rating, y = price)) +
#   geom_point(aes(alpha = 0.4))
  


```

```{r}

# listings_clean %>% 
#   group_by(property_type) %>%
#   summarise(count = n()) %>% 
#   arrange(desc(count))


listings_clean <- listings_clean %>%
  mutate(prop_type_simplified = case_when(
    property_type %in% c("Entire rental unit","Private room in rental unit", "Entire residential home","Entire condominium (condo)") ~ property_type, 
    TRUE ~ "Other"
  ))
  
```

```{r, out.width = '80%'}

leaflet(data = filter(listings_clean)) %>% 
  addProviderTiles("OpenStreetMap.Mapnik") %>% 
  addCircleMarkers(lng = ~longitude, 
                   lat = ~latitude, 
                   radius = 1, 
                   fillColor = "blue", 
                   fillOpacity = 0.4, 
                   popup = ~listing_url,
                   label = ~property_type)
```